on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- -v -y
          ln -s $HOME/.elan/bin/* /usr/local/bin;

      - name: Install python Lean dependencies
        run: python -m pip install --upgrade pip requests markdown2 toml mathlibtools toposort invoke

      - name: link and fetch mathlib
        run: |
          ln -s lean-liquid project
          cd project && leanproject get-m && cd ..
          inv decls

      - name: Install Leanblueprint and dependencies
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk update
            apk add --update py3-pip git
            python3 -m pip install --upgrade pip requests wheel
            apk add pkgconfig graphviz graphviz-dev gcc musl-dev && \
            python3 -m pip install pygraphviz --install-option="--library-path=/usr/lib/graphviz/"
            python3 -m pip install mathlibtools invoke git+https://github.com/plastex/plastex.git git+https://github.com/PatrickMassot/leanblueprint.git 
            inv pdf; cp print/blueprint.bbl src/web.bbl; inv qweb

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github_token }}
          publish_dir: ./web