name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Prepare cache
        uses: actions/cache@v2
        id: cache-id
        with:
          path: ${{ runner.temp }}/cache
          key: ${{ runner.os }}-cache-key-v1.0

      - name: Install prerequisites
        uses: airvzxf/cache-anything-new-action@v1.0.1
        with:
          script: 'install.sh'
          is_cached: ${{ steps.cache-id.outputs.cache-hit }}
          cache: ${{ runner.temp }}/cache-directory-example
          snapshot: '/'
          exclude: '/boot /data /dev /mnt /proc /run /sys'

      - name: Link and fetch mathlib
        run: sh ./workflows/fetch.sh
       
      - run: inv web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web