on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- -v -y
          sudo ln -s $HOME/.elan/bin/* /usr/local/bin;

      - name: Install python Lean dependencies
        run: python -m pip install --upgrade pip requests markdown2 toml mathlibtools toposort invoke

      - name: Install Leanblueprint
        run: |
          sudo apt-get install graphviz graphviz-dev
          python -m pip install pygraphviz
          python -m pip install git+https://github.com/plastex/plastex.git git+https://github.com/PatrickMassot/leanblueprint.git 

      - name: Link and fetch mathlib
        run: |
          leanproject get leanprover-community/lean-liquid
          ln -s lean-liquid project
          cd project && leanproject get-m && cd ..
          inv decls

      - name: Generate pdf in tex env
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk update
            apk add --update py3-pip git
            python3 -m pip install --upgrade pip requests wheel invoke
            inv pdf; cp print/blueprint.bbl src/web.bbl

      - name: Generate web
        run: |
            inv qweb
            cp print/blueprint.pdf web/

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.github_token }}
          publish_dir: ./web
